Repository rhinstaller/initial-setup, pull requests merged in 2020-06, with the labels that each got.

#98 Migrate translations to Weblate
  Makefile
  README.rst
  branch-config.mk
  zanata.xml
Labels: Port to RHEL8, master

#99 Add COPR daily builds badge
  README.rst
Labels: master

#100 Switch to Weblate - RHEL8 version
  MANIFEST.in
  Makefile
  README.rst
  branch-config.mk
Labels: rhel8-branch

#102 Remove hard coded name of the translation repo in tmp
  Makefile
Labels: master

#105 Add PEP8 Speaks configuration
  .pep8speaks.yml
Labels: master

#104 Add PEP8 Speaks configuration
  .pep8speaks.yml
Labels: rhel8-branch

#103 Disable multi TTY handler when running in SSH session
  initial_setup/__init__.py
  initial_setup/tui/tui.py
  scripts/s390/initial-setup.csh
  scripts/s390/initial-setup.sh
Labels: port to Fedora, rhel8-branch
